# Generated by Django 5.2.3 on 2025-06-18 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 14, 11, 0, 379169), verbose_name='Upload Date'),
        ),
    ]
